#!/bin/bash
set -ex

ROOT=$(cd "$(dirname "$0")"; pwd)

pushd () {
	command pushd "$@" > /dev/null
}

popd () {
	command popd "$@" > /dev/null
}

sync_dotfiles(){
	rsync -aq --exclude-from=rsyncexclude  . ~
	rsync -qa --exclude-from=rsyncexclude .code/ ~/Library/Application\ Support/Code/User/
}

install_mac(){
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew install bash-completion git wget go python python3 iproute2mac

	sync_dotfiles

	_install_ipalias

	_install_vundle

	mkdir ~/go
}

_install_ipalias(){
	pushd /Library/LaunchDaemons
	cat $ROOT/dev.ipalias.plist | sudo tee -a dev.ip.alias.plist
	sudo chmod 0644 dev.ip.alias.plist
	sudo launchctl load dev.ip.alias.plist
	popd
}

_install_vundle(){
	git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	vim +PluginInstall +qall
}

pushd $ROOT

if [ "$1" = "sync" ]
then
	sync_dotfiles
elif [ "$1" = "install" ]
then
	install_mac
else
	echo "Invalid action"
	exit 1
fi

popd
