#!/bin/bash
set -e

ROOT=$(cd "$(dirname "$0")"; pwd)

pushd () {
	command pushd "$@" > /dev/null
}

popd () {
	command popd "$@" > /dev/null
}

sync_confs(){
	rsync -aq --exclude-from=rsyncexclude  . ~
}

install(){
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew install bash-completion git wget iproute2mac

	sync_confs

	_install_ipalias

	_install_vundle

	mkdir ~/go
}

LOOPBACK_ALIAS=loopback.alias.plist

_install_ipalias(){
	pushd /Library/LaunchDaemons
	sudo cp $ROOT/$LOOPBACK_ALIAS $LOOPBACK_ALIAS
	sudo chmod 0644 $LOOPBACK_ALIAS
	sudo launchctl load $LOOPBACK_ALIAS
	popd
}

_install_vundle(){
	git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	vim +PluginInstall +qall
}

pushd $ROOT

if [ "$1" = "sync" ]
then
	sync_confs
elif [ "$1" = "install" ]
then
	install
else
	echo "Invalid action"
	exit 1
fi

popd
