#!/bin/bash
# set -ex

ROOT=$(cd "$(dirname "$0")"; pwd)
OS=`uname -s`

if [ "$OS" = "Darwin" ]
then
    postfix="mac"
else
    echo "OS not suported"
    exit 1
fi

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

sync_dotfiles(){
    pushd $ROOT/common
    rsync -aq --exclude-from=rsyncexclude  . ~
    popd
    pushd $ROOT/$postfix
    rsync -aq --exclude-from=rsyncexclude  . ~
    popd
}

install_mac(){
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install bash-completion git wget go python python3 iproute2mac

    sync_dotfiles

    _install_vundle

    mkdir ~/go
}

_install_vundle(){
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
}

pushd $ROOT

if [ "$1" = "sync" ]
then
    sync_dotfiles
elif [ "$1" = "install" ]
then
    install_$postfix
else
    echo "Invalid action"
    exit 1
fi

popd
