alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias etcdctl-docker='etcdctl --endpoint http://d.w.w:2379'
export GOPATH=~/goproject
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/wentworth/.docker/machine/machines/dev"
export DOCKER_MACHINE_NAME="dev"
export PATH=$PATH:$GOPATH/bin